import Footprint from './Footprint.js';
import FootprintProps from './FootprintProps.js';
import { mat4 } from 'gl-matrix';
declare class FootprintSetGL {
    static ELEM_SIZE: number;
    static BYTES_X_ELEM: number;
    static CONVEXPOLY_ELEM_SIZE: number;
    ready: boolean;
    footprintsetProps: FootprintProps;
    name: string;
    description: string;
    provider: string;
    tapRepo: any;
    footprintPolygons: Footprint[];
    indexes: Uint32Array;
    totPoints: number;
    totConvexPoints: number;
    footprintsInPix256: Map<number, Footprint[]>;
    attribLocations: {
        position: number | WebGLUniformLocation;
        selected: number;
        pointSize: number;
        color: number[] | WebGLUniformLocation;
    };
    gl: WebGL2RenderingContext;
    shaderProgram: WebGLProgram;
    vertexCataloguePositionBuffer: WebGLBuffer;
    vertexhoveredCataloguePositionBuffer: WebGLBuffer;
    indexBuffer: WebGLBuffer;
    hoveredVertexPositionBuffer: WebGLBuffer;
    hoveredIndexBuffer: WebGLBuffer;
    selectedVertexPositionBuffer: WebGLBuffer;
    selectedIndexBuffer: WebGLBuffer;
    vertexCataloguePosition: Float32Array;
    nPrimitiveFlags: number;
    hoveredIndexes: number[];
    selectedIndexes: number[];
    extHoveredIndexes: number[];
    oldMouseCoords: any;
    healpixDensityMap: any;
    hoveredFootprints: never[];
    hoveredIndex: never[];
    hoveredVertexPosition: never[];
    totHoveredPoints: number;
    selectedFootprints: never[];
    selectedIndex: never[];
    selectedVertexPosition: never[];
    totSelectedPoints: number;
    constructor(tablename: string, tabledesc: string, tapRepo: any, tapMetadataList: any);
    private initFootprintArrays;
    private initGLBuffers;
    private initShaders;
    private loadShaderFromDOM;
    addFootprint(in_footprint: Footprint): void;
    addFootprints(in_data: any[]): void;
    clearFootprints(): void;
    private initBuffer;
    private enableShader;
    draw(in_mMatrix: mat4, in_mouseHelper: any): void;
}
export default FootprintSetGL;
//# sourceMappingURL=FootprintSetGL.d.ts.map