import Footprint from './Footprint.js';
import FootprintProps from './FootprintProps.js';
import { mat4 } from 'gl-matrix';
import { TapRepo } from '../tap/TapRepo.js';
import TapMetadataList from '../tap/TapMetadataList.js';
import TapMetadata from '../tap/TapMetadata.js';
type GL = WebGL2RenderingContext;
declare class FootprintSetGL {
    static ELEM_SIZE: number;
    static BYTES_X_ELEM: number;
    static CONVEXPOLY_ELEM_SIZE: number;
    ready: boolean;
    footprintsetProps: FootprintProps;
    name: string;
    description: string;
    tapRepo: TapRepo;
    footprintPolygons: Footprint[];
    indexes: Uint32Array;
    totPoints: number;
    totConvexPoints: number;
    footprintsInPix256: Map<number, Footprint[]>;
    gl: GL;
    vertexCataloguePositionBuffer: WebGLBuffer;
    vertexhoveredCataloguePositionBuffer: WebGLBuffer;
    indexBuffer: WebGLBuffer;
    hoveredVertexPositionBuffer: WebGLBuffer;
    hoveredIndexBuffer: WebGLBuffer;
    selectedVertexPositionBuffer: WebGLBuffer;
    selectedIndexBuffer: WebGLBuffer;
    vertexCataloguePosition: Float32Array;
    nPrimitiveFlags: number;
    hoveredIndexes: number[];
    selectedIndexes: number[];
    extHoveredIndexes: number[];
    oldMouseCoords: any;
    healpixDensityMap: any;
    hoveredFootprints: never[];
    hoveredIndex: never[];
    hoveredVertexPosition: never[];
    totHoveredPoints: number;
    selectedFootprints: never[];
    selectedIndex: never[];
    selectedVertexPosition: never[];
    totSelectedPoints: number;
    _isVisible: boolean;
    constructor(tablename: string, tabledesc: string, tapRepo: TapRepo, tapMetadataList: TapMetadataList);
    private initFootprintArrays;
    private initGLBuffers;
    setIsVisible(visibility: boolean): void;
    get isVisible(): boolean;
    addFootprint(in_footprint: Footprint): void;
    addFootprints(in_data: any[], columnsmeta: TapMetadata[]): void;
    clearFootprints(): void;
    private initBuffer;
    draw(in_mMatrix: mat4, in_mouseHelper: any): void;
}
export default FootprintSetGL;
//# sourceMappingURL=FootprintSetGL.d.ts.map