import HiPS from './HiPS.js';
type Mat4 = Float32Array;
export default class Tile {
    private _hips;
    private _tileno;
    private _baseurl;
    private _order;
    private _format;
    private _maxorder;
    private _isGalacticHips;
    private _ready;
    private _abort;
    private _image;
    private _textureLoaded;
    private _texture?;
    private _texurl;
    private _hipsShaderIndex;
    private _cacheTime0?;
    private _inView;
    private _amIStillInFoV_requsetID;
    private vertexPosition;
    private vertexPositionBuffer;
    private vertexIndices;
    private vertexIndexBuffer?;
    opacity: number;
    constructor(tileno: number, order: number, hips: HiPS);
    destroyIntervals(): void;
    getReadyState(): boolean;
    get cacheTime0(): number | undefined;
    resetCacheTime0(): void;
    setCacheTime0(): void;
    private initImage;
    private imageLoaded;
    private textureLoaded;
    private initModelBuffer;
    private computeVertexIndices;
    private setupPositionAndTexture4Quadrant2;
    get inView(): boolean;
    private moveToCache;
    amIStillInFoV(): void;
    draw(visibleOrder: number, visibleTilesMap: Map<number, number[]>, pMatrix: Mat4, vMatrix: Mat4, mMatrix: Mat4, colorMapIdx: number): void;
    private drawChildren;
}
export {};
//# sourceMappingURL=Tile.d.ts.map