import { AbstractSkyEntity, SkyEntityDrawInput } from '../AbstractSkyEntity.js';
import { FoV } from '../FoV.js';
import { VisibleTilesManager } from '../hips/VisibleTilesManager.js';
export declare class HealpixGridSingleton extends AbstractSkyEntity {
    static ELEM_SIZE: number;
    static BYTES_X_ELEM: number;
    private _visibleorder;
    private showGrid;
    private _shaderProgram;
    private fragmentShader;
    private vertexShader;
    private defaultColor;
    private gridText;
    private _attribLocations;
    private _nPrimitiveFlags;
    private _vertexCataloguePositionBuffer;
    private _indexBuffer;
    private _vertexCataloguePosition;
    private _indexes;
    private fovObj;
    static INITIAL_FOV: number;
    static RADIUS: number;
    static INITIAL_POSITION: [number, number, number];
    static INITIAL_PhiRad: number;
    static INITIAL_ThetaRad: number;
    private _visibleTilesManager;
    constructor(webgl: WebGL2RenderingContext);
    init(): void;
    get RADIUS(): number;
    get INITIAL_POSITION(): [number, number, number];
    get INITIAL_PhiRad(): number;
    get INITIAL_ThetaRad(): number;
    refreshFoV(): FoV;
    getFoV(): FoV;
    getMinFoV(): number;
    private initShaders;
    initBuffers(pixels: number[], order: number): void;
    private refresh;
    private enableShader;
    isVisible(): boolean;
    toggleShowGrid(): void;
    get visibleTilesManager(): VisibleTilesManager;
    draw(input: SkyEntityDrawInput): void;
    get visibleorder(): number;
}
//# sourceMappingURL=HealpixGridSingleton.d.ts.map