import { HiPSDescriptor } from './model/hips/HiPSDescriptor.js';
import { FoV } from './model/FoV.js';
import Point from './model/Point.js';
import { CatalogueGL } from './model/catalogues/CatalogueGL.js';
import type { PointCoordinates } from './AstroSphere.js';
import { FootprintSetGL, HoveredFootprintDetail } from './model/footprints/FootprintSetGL.js';
export declare class AstroViewer {
    private astroSphere;
    private canvas;
    private webgl;
    private rafId;
    run(): number;
    showCatalogue(catalogue: CatalogueGL): void;
    hideCatalogue(catalogue: CatalogueGL, isVisible: boolean): void;
    deleteCatalogue(catalogue: CatalogueGL): void;
    changeCatalogueRA(catalogue: CatalogueGL, raColumnName: string): void;
    changeCatalogueDec(catalogue: CatalogueGL, decColumnName: string): void;
    changeCatalogueColor(catalogue: CatalogueGL, hexColor: string): void;
    setCatalogueShapeHue(catalogue: CatalogueGL, metadataColumnName: string): void;
    setCatalogueShapeSize(catalogue: CatalogueGL, metadataColumnName: string): void;
    showFootprintSet(footprintSet: FootprintSetGL): void;
    hideFootprintSet(footprintSet: FootprintSetGL, isVisible: boolean): void;
    deleteFootprintSet(footprintSet: FootprintSetGL): void;
    changeFootprintSetColor(footprintSet: FootprintSetGL, hexColor: string): void;
    getHoveredFootprints(): HoveredFootprintDetail[];
    getDefaultHiPSURL(): string;
    activateHiPS(hipsDescriptor: HiPSDescriptor): void;
    loadHiPS(baseUrl: string): Promise<void>;
    goTo(raDeg: number, decDeg: number): void;
    getCenterCoordinates(): PointCoordinates | undefined;
    getCoordinatesFromMouse(): PointCoordinates | undefined;
    toggleHealpixGrid(): void;
    isHealpixGridVisible(): boolean;
    toggleEquatorialGrid(): void;
    isEquatorialGridVisible(): boolean;
    getFoV(): FoV;
    getFoVPolygon(): Point[];
    changeFoV(deg: number): void;
    changeFoV2(deg: number): void;
    changeFoV3(deg: number): void;
    getInsideSphere(): boolean;
    toggleInsideSphere(): void;
    constructor(canvasDomId: string);
    private init;
    private initListeners;
    private tick;
    private drawScene;
}
//# sourceMappingURL=AstroViewer.d.ts.map