import Camera from "./Camera.js";
import { AstroCoords, HMS, SphericalCoords, DMS } from "./utils/Utils.js";
import { HiPS } from "./model/hips/HiPS.js";
import { HiPSDescriptor } from "./model/hips/HiPSDescriptor.js";
import { SphereFoV } from "./model/SphereFoV.js";
import { Point } from "./model/Point.js";
import { CatalogueGL } from "./model/catalogues/CatalogueGL.js";
import { FootprintSetGL, HoveredFootprintDetail } from "./model/footprints/FootprintSetGL.js";
import { EquatorialGrid } from "./model/grid/EquatorialGrid.js";
import { HealpixGrid } from "./model/grid/HealpixGrid.js";
import type { GridLabelContainers } from "./model/grid/GridTextHelper.js";
import { ColorMap } from "./model/ColorMaps.js";
import type { WMTSLayerConfig, XYZDebugStats, XYZLayerConfig } from "./model/earth/XYZConfig.js";
import type { HiPSDebugStats } from "./model/hips/HiPSConfig.js";
import { XYZMapDescriptor } from "./model/earth/XYZMapDescriptor.js";
import { XYZMap } from "./model/earth/XYZMap.js";
import { MeshHiPS } from "./model/meships/MeshHiPS.js";
import { MeshHiPSDescriptor } from "./model/meships/MeshHiPSDescriptor.js";
import type { MeshHiPSDebugStats } from "./model/meships/MeshHiPSTypes.js";
import { TerraPolylineSetGL } from "./model/terra/TerraPolylineSetGL.js";
import { SatelliteObjectGL } from "./model/terra/SatelliteObjectGL.js";
import { SensorConeGL } from "./model/terra/SensorConeGL.js";
export type PointCoordinates = {
    astroDeg: AstroCoords;
    raHMS: HMS;
    decDMS: DMS;
    sphericalDeg: SphericalCoords;
};
export type CameraChangedDetail = {
    colorMap: ColorMap;
    fovDeg: number;
    fovXDeg: number;
    fovYDeg: number;
    position: [number, number, number];
    vMatrix: Float32Array;
    pMatrix: Float32Array;
    mMatrix: Float32Array;
    camera: Camera;
    timestamp: number;
    centralPoint: Point;
    mouseHoverPoint: PointCoordinates | undefined;
    getFoVPolygon: Point[];
};
export type AstroSphereOptions = {
    gridLabelContainers?: GridLabelContainers;
};
/**
 * AstroSphere — main WebGL scene controller (TS port)
 */
declare class AstroSphere {
    private static readonly MIN_WHEEL_SCALE;
    private static readonly MAX_WHEEL_SCALE;
    private _camera;
    private _perspectiveMatrixManager;
    private centralPoinCoords;
    private mousePointCoords;
    private canvas;
    private _healpixGrid;
    private _equatorialGrid;
    private mouseHelper;
    private mouseDown;
    private lastMouseX;
    private lastMouseY;
    private inertiaX;
    private inertiaY;
    private zoomInertia;
    private pointerDownX;
    private pointerDownY;
    private pointerDownAt;
    private _activeHiPS;
    private _activeXYZ2;
    private _activeMeshHiPS;
    private _activeBaseLayer;
    private startup;
    private fov;
    private activeCatalogues;
    private activeFootprintSets;
    private activePolylineSets;
    private activeSensorCones;
    private activeSatelliteObjects;
    private _webgl;
    private _selectedColorMap;
    private _cameraStatusChanged;
    private lastCameraChangedAt;
    private lastCameraMotionAt;
    private lastHoveredSource;
    private lastHoveredCatalogue;
    private zoomSensitivity;
    private lockedEastWestRaDeg;
    private lockedNorthSouthDecDeg;
    private keepCameraNorthUp;
    private gridLabelContainers?;
    constructor(canvas: HTMLCanvasElement, webgl: WebGL2RenderingContext, options?: AstroSphereOptions);
    private initCamera;
    setCamera(camera: Camera): void;
    setCameraRotationSensitivity(value: number): void;
    getCameraRotationSensitivity(): number;
    get healpixGrid(): HealpixGrid;
    get equatorialGrid(): EquatorialGrid;
    private updateCentralPoint;
    private updateLastMousePoint;
    private clearLastMousePoint;
    getCentralPointCoordinates(): PointCoordinates | undefined;
    getLastMousePointCoordinates(): PointCoordinates | undefined;
    private clamp;
    private computeZoomStep;
    setZoomSensitivity(value: number): void;
    getZoomSensitivity(): number;
    private filterRotationDeltaByAstroLocks;
    private projectModelDirectionToScreen;
    private projectModelPointToScreen;
    private enforceAstronomicalRotationLocks;
    private enforceCameraNorthUp;
    private emitCameraChanged;
    private addEventListeners;
    getPhiThetaDeg(canvas: HTMLCanvasElement): SphericalCoords;
    private collectViewportSphericalSamples;
    activateHiPS(hipsDescriptor: HiPSDescriptor): void;
    activateXYZ(config: XYZLayerConfig): void;
    activateXYZ2(config: XYZMapDescriptor): void;
    activateMeshHiPS(descriptor: MeshHiPSDescriptor): void;
    activateWMTS(config: WMTSLayerConfig): void;
    showCatalogue(cat: CatalogueGL): Promise<CatalogueGL>;
    deleteCatalogue(catalogue: CatalogueGL): void;
    showFootprintSet(fset: FootprintSetGL): Promise<FootprintSetGL>;
    deleteFootprintSet(footprintSet: FootprintSetGL): void;
    showPolylineSet(polylineSet: TerraPolylineSetGL): Promise<TerraPolylineSetGL>;
    deletePolylineSet(polylineSet: TerraPolylineSetGL): void;
    showSensorCone(sensorCone: SensorConeGL): Promise<SensorConeGL>;
    deleteSensorCone(sensorCone: SensorConeGL): void;
    showSatelliteObject(satelliteObject: SatelliteObjectGL): Promise<SatelliteObjectGL>;
    deleteSatelliteObject(satelliteObject: SatelliteObjectGL): void;
    getHoveredFootprints(): HoveredFootprintDetail[];
    goTo(raDeg: number, decDeg: number): void;
    getActiveCoordinateMode(): "equatorial" | "galactic" | "lonlat";
    resetAxesOrientation(): void;
    setKeepCameraNorthUp(enabled: boolean): void;
    isKeepCameraNorthUp(): boolean;
    getFoV(): SphereFoV;
    getFoVPolygon(): Point[];
    changeFoV(deg: number): void;
    changeFoV2(deg: number): void;
    changeFoV3(deg: number): void;
    getInsideSphere(): boolean;
    toggleInsideSphere(): void;
    setCameraPosition(pos: [number, number, number]): void;
    setCameraMatrix(viewMatrix: Float32Array): void;
    private _refreshingStatus;
    applyFullCameraState(detail: CameraChangedDetail, applyColor: boolean): void;
    getCurrentStatus(): CameraChangedDetail | null;
    changeColorMap(cm: ColorMap): void;
    private prevFov;
    private prevCentralRaDeg;
    private prevCentralDecDeg;
    get activeHiPS(): HiPS | null;
    get activeXYZ(): XYZMap | null;
    get activeMeshHiPS(): MeshHiPS | null;
    isLonLatGridVisible(): boolean;
    toggleLonLatGrid(): boolean;
    setEastWestRotationLocked(locked: boolean): void;
    isEastWestRotationLocked(): boolean;
    setNorthSouthRotationLocked(locked: boolean): void;
    isNorthSouthRotationLocked(): boolean;
    getXYZDebugStats(): XYZDebugStats;
    getHiPSDebugStats(): HiPSDebugStats | null;
    getMeshHiPSDebugStats(): MeshHiPSDebugStats | null;
    draw(canvas: HTMLCanvasElement): void;
    private emitHoveredSourceIfChanged;
}
export default AstroSphere;
