import { HiPSDescriptor } from './model/hips/HiPSDescriptor.js';
import { FoV } from './model/FoV.js';
import { Point } from './model/Point.js';
import { CatalogueGL } from './model/catalogues/CatalogueGL.js';
import type { CameraChangedDetail, PointCoordinates } from './AstroSphere.js';
import { FootprintSetGL, HoveredFootprintDetail } from './model/footprints/FootprintSetGL.js';
import { MetadataManager } from './model/MetadataManager.js';
import Camera from './Camera.js';
import { ReadonlyMat4 } from 'gl-matrix';
import { ColorMap, ColorMapName } from './model/ColorMaps.js';
import { HiPS } from './model/hips/HiPS.js';
export declare class AstroViewer {
    private astroSphere;
    private canvas;
    private webgl;
    private rafId;
    private webglContextList;
    private viewfinderEl;
    private viewfinderVisible;
    private viewfinderColor;
    run(): number;
    createCatalogue(catalogueName: string, catalogueDescription: string, providerUrl: string, metadataManager: MetadataManager): CatalogueGL;
    showCatalogue(catalogue: CatalogueGL): void;
    hideCatalogue(catalogue: CatalogueGL, isVisible: boolean): void;
    deleteCatalogue(catalogue: CatalogueGL): void;
    changeCatalogueRA(catalogue: CatalogueGL, raColumnName: string): CatalogueGL;
    changeCatalogueDec(catalogue: CatalogueGL, decColumnName: string): CatalogueGL;
    changeCatalogueColor(catalogue: CatalogueGL, hexColor: string): CatalogueGL;
    setCatalogueShapeHue(catalogue: CatalogueGL, metadataColumnName: string): CatalogueGL;
    setCatalogueShapeSize(catalogue: CatalogueGL, metadataColumnName: string): CatalogueGL;
    createFootprintSet(footprintSetName: string, footprintSetDescription: string, providerUrl: string, metadataManager: MetadataManager): FootprintSetGL;
    showFootprintSet(footprintSet: FootprintSetGL): void;
    hideFootprintSet(footprintSet: FootprintSetGL, isVisible: boolean): void;
    deleteFootprintSet(footprintSet: FootprintSetGL): void;
    changeFootprintSetColor(footprintSet: FootprintSetGL, hexColor: string): void;
    getHoveredFootprints(): HoveredFootprintDetail[];
    getDefaultHiPSURL(): string;
    activateHiPS(hipsDescriptor: HiPSDescriptor): void;
    loadHiPS(baseUrl: string): Promise<string>;
    changeColorMap(colorMapName: ColorMapName): void;
    changeCustomColorMap(colorMap: ColorMap): void;
    getActiveHiPS(): HiPS | null;
    setCamera(camera: Camera): void;
    setCameraPosition(pos: [number, number, number]): void;
    setCameraMatrix(viewMatrix: Float32Array): void;
    restoreAstroViewerState(detail: CameraChangedDetail, applyColorMap: boolean): void;
    getCurrentAstroViewerStatus(): CameraChangedDetail | null;
    goTo(raDeg: number, decDeg: number): void;
    getCenterCoordinates(): PointCoordinates | undefined;
    getCoordinatesFromMouse(): PointCoordinates | undefined;
    setModelMatrix(modelMatrix: ReadonlyMat4): void;
    toggleHealpixGrid(): void;
    isHealpixGridVisible(): boolean;
    toggleEquatorialGrid(): void;
    isEquatorialGridVisible(): boolean;
    getFoV(): FoV;
    getFoVPolygon(): Point[];
    changeFoV(deg: number): void;
    changeFoV2(deg: number): void;
    changeFoV3(deg: number): void;
    getInsideSphere(): boolean;
    toggleInsideSphere(): void;
    toggleViewfinder(): boolean;
    setViewfinderVisible(visible: boolean): void;
    isViewfinderVisible(): boolean;
    setViewfinderColor(color: string): void;
    getViewfinderColor(): string;
    constructor(canvasEl: HTMLCanvasElement);
    private init;
    private initViewfinder;
    private syncViewfinderVisibility;
    private syncViewfinderColor;
    private initListeners;
    private tick;
    private drawScene;
}
//# sourceMappingURL=AstroViewer.d.ts.map