import { HiPSDescriptor } from './model/hips/HiPSDescriptor.js';
import { SphereFoV } from './model/SphereFoV.js';
import { Point } from './model/Point.js';
import { CatalogueGL } from './model/catalogues/CatalogueGL.js';
import type { CameraChangedDetail, PointCoordinates } from './AstroSphere.js';
import { FootprintSetGL, HoveredFootprintDetail } from './model/footprints/FootprintSetGL.js';
import { MetadataManager } from './model/MetadataManager.js';
import Camera from './Camera.js';
import { ReadonlyMat4 } from 'gl-matrix';
import { ColorMap, ColorMapName } from './model/ColorMaps.js';
import { HiPS } from './model/hips/HiPS.js';
import type { WMTSLayerConfig, XYZDebugStats, XYZLayerConfig } from './model/earth/XYZConfig.js';
import type { HiPSDebugStats } from './model/hips/HiPSConfig.js';
import { XYZMap } from './model/earth/XYZMap.js';
import { TerraPointSetGL } from './model/terra/TerraPointSetGL.js';
import { TerraFootprintSetGL } from './model/terra/TerraFootprintSetGL.js';
import { TerraPolylineSetGL } from './model/terra/TerraPolylineSetGL.js';
import { SatelliteObjectGL, type SatelliteObjectOptions } from './model/terra/SatelliteObjectGL.js';
import { SensorConeGL, type SensorConeOptions } from './model/terra/SensorConeGL.js';
import type { MeshHiPSConfig, MeshHiPSDebugStats } from './model/meships/MeshHiPSTypes.js';
export declare class AstroViewer {
    private astroSphere;
    private canvas;
    private webgl;
    private rafId;
    private webglContextList;
    private viewfinderEl;
    private viewfinderVisible;
    private viewfinderColor;
    run(): number;
    createCatalogue(catalogueName: string, catalogueDescription: string, providerUrl: string, metadataManager: MetadataManager): CatalogueGL;
    showCatalogue(catalogue: CatalogueGL): void;
    hideCatalogue(catalogue: CatalogueGL, isVisible: boolean): void;
    deleteCatalogue(catalogue: CatalogueGL): void;
    changeCatalogueRA(catalogue: CatalogueGL, raColumnName: string): CatalogueGL;
    changeCatalogueDec(catalogue: CatalogueGL, decColumnName: string): CatalogueGL;
    changeCatalogueColor(catalogue: CatalogueGL, hexColor: string): CatalogueGL;
    setCatalogueShapeHue(catalogue: CatalogueGL, metadataColumnName: string): CatalogueGL;
    setCatalogueShapeSize(catalogue: CatalogueGL, metadataColumnName: string): CatalogueGL;
    createFootprintSet(footprintSetName: string, footprintSetDescription: string, providerUrl: string, metadataManager: MetadataManager): FootprintSetGL;
    showFootprintSet(footprintSet: FootprintSetGL): void;
    hideFootprintSet(footprintSet: FootprintSetGL, isVisible: boolean): void;
    deleteFootprintSet(footprintSet: FootprintSetGL): void;
    createTerraPointSet(pointSetName: string, pointSetDescription: string, providerUrl: string, metadataManager: MetadataManager): TerraPointSetGL;
    showTerraPointSet(pointSet: TerraPointSetGL): void;
    hideTerraPointSet(pointSet: TerraPointSetGL, isVisible: boolean): void;
    deleteTerraPointSet(pointSet: TerraPointSetGL): void;
    createTerraFootprintSet(footprintSetName: string, footprintSetDescription: string, providerUrl: string, metadataManager: MetadataManager): TerraFootprintSetGL;
    showTerraFootprintSet(footprintSet: TerraFootprintSetGL): void;
    hideTerraFootprintSet(footprintSet: TerraFootprintSetGL, isVisible: boolean): void;
    deleteTerraFootprintSet(footprintSet: TerraFootprintSetGL): void;
    createTerraPolylineSet(polylineSetName: string, polylineSetDescription: string, providerUrl: string, metadataManager: MetadataManager): TerraPolylineSetGL;
    showTerraPolylineSet(polylineSet: TerraPolylineSetGL): void;
    hideTerraPolylineSet(polylineSet: TerraPolylineSetGL, isVisible: boolean): void;
    deleteTerraPolylineSet(polylineSet: TerraPolylineSetGL): void;
    changeTerraPolylineSetColor(polylineSet: TerraPolylineSetGL, hexColor: string): TerraPolylineSetGL;
    createSensorCone(options: SensorConeOptions): SensorConeGL;
    showSensorCone(sensorCone: SensorConeGL): void;
    hideSensorCone(sensorCone: SensorConeGL, isVisible: boolean): void;
    deleteSensorCone(sensorCone: SensorConeGL): void;
    createSatelliteObject(options: SatelliteObjectOptions): SatelliteObjectGL;
    showSatelliteObject(satelliteObject: SatelliteObjectGL): void;
    hideSatelliteObject(satelliteObject: SatelliteObjectGL, isVisible: boolean): void;
    deleteSatelliteObject(satelliteObject: SatelliteObjectGL): void;
    changeFootprintSetColor(footprintSet: FootprintSetGL, hexColor: string): void;
    getHoveredFootprints(): HoveredFootprintDetail[];
    getDefaultHiPSURL(): string;
    activateHiPS(hipsDescriptor: HiPSDescriptor): void;
    activateXYZ(config: XYZLayerConfig): void;
    activateXYZ2(config: XYZLayerConfig & {
        name?: string;
    }): void;
    activateWMTS(config: WMTSLayerConfig): void;
    activateMeshHiPS(config: MeshHiPSConfig): void;
    setXYZMaxConcurrentRequests(value: number): void;
    getXYZMaxConcurrentRequests(): number;
    getXYZDebugStats(): XYZDebugStats;
    getHiPSDebugStats(): HiPSDebugStats | null;
    getMeshHiPSDebugStats(): MeshHiPSDebugStats | null;
    loadHiPS(baseUrl: string): Promise<string>;
    loadMeshHiPS(baseUrl: string, config?: Omit<MeshHiPSConfig, 'baseUrl'>): Promise<string>;
    changeColorMap(colorMapName: ColorMapName): void;
    changeCustomColorMap(colorMap: ColorMap): void;
    getActiveHiPS(): HiPS | null;
    getActiveXYZ(): XYZMap | null;
    setCamera(camera: Camera): void;
    setCameraPosition(pos: [number, number, number]): void;
    setCameraMatrix(viewMatrix: Float32Array): void;
    restoreAstroViewerState(detail: CameraChangedDetail, applyColorMap: boolean): void;
    getCurrentAstroViewerStatus(): CameraChangedDetail | null;
    goTo(raDeg: number, decDeg: number): void;
    getActiveCoordinateMode(): 'equatorial' | 'galactic' | 'lonlat';
    getCenterCoordinates(): PointCoordinates | undefined;
    getCoordinatesFromMouse(): PointCoordinates | undefined;
    setModelMatrix(modelMatrix: ReadonlyMat4): void;
    toggleHealpixGrid(): void;
    isHealpixGridVisible(): boolean;
    toggleEquatorialGrid(): void;
    isEquatorialGridVisible(): boolean;
    toggleLonLatGrid(): boolean;
    isLonLatGridVisible(): boolean;
    setEastWestRotationLocked(locked: boolean): void;
    isEastWestRotationLocked(): boolean;
    setNorthSouthRotationLocked(locked: boolean): void;
    isNorthSouthRotationLocked(): boolean;
    resetAxesOrientation(): void;
    setKeepCameraNorthUp(enabled: boolean): void;
    isKeepCameraNorthUp(): boolean;
    getFoV(): SphereFoV;
    getFoVPolygon(): Point[];
    changeFoV(deg: number): void;
    changeFoV2(deg: number): void;
    changeFoV3(deg: number): void;
    getInsideSphere(): boolean;
    toggleInsideSphere(): void;
    toggleViewfinder(): boolean;
    setViewfinderVisible(visible: boolean): void;
    isViewfinderVisible(): boolean;
    setViewfinderColor(color: string): void;
    getViewfinderColor(): string;
    setRotationSensitivity(value: number): void;
    getRotationSensitivity(): number;
    setZoomSensitivity(value: number): void;
    getZoomSensitivity(): number;
    constructor(canvasEl: HTMLCanvasElement);
    private init;
    private initViewfinder;
    private syncViewfinderVisibility;
    private syncViewfinderColor;
    private initListeners;
    private tick;
    private drawScene;
}
