import { Healpix } from 'healpixjs';
import type { mat4 } from 'gl-matrix';
import Camera from './Camera.js';
type GL = WebGLRenderingContext | WebGL2RenderingContext;
declare class Global {
    private _pMatrix;
    private _mvMatrix;
    private _model;
    private _camera;
    private _gl;
    private _rayPicker;
    private _healpix;
    private _order;
    private _hipsStack?;
    private _baseUrl;
    private _selectionnside;
    private _healpix4footprints;
    private _showConvexPolygons;
    private _showPointsInPolygons;
    private _defaultHips;
    private _blendMode;
    private _useCORSProxy;
    private _corsProxyUrl;
    private _maxDecimals;
    private _debug;
    private _insideSphere;
    private _version;
    HIPS_REF_ORDER: number;
    constructor();
    init(): void;
    get version(): string;
    set corsProxyUrl(url: string);
    get corsProxyUrl(): string;
    get useCORSProxy(): boolean;
    set useCORSProxy(enabled: boolean);
    get debug(): boolean;
    getHealpix(order: number): Healpix;
    get MAX_DECIMALS(): number;
    get pMatrix(): mat4 | null;
    set pMatrix(in_pMatrix: mat4 | null);
    get mvMatrix(): mat4 | null;
    set mvMatrix(in_mvMatrix: mat4 | null);
    get model(): unknown;
    set model(in_model: unknown);
    get camera(): Camera | null;
    set camera(in_camera: Camera | null);
    get gl(): GL | null;
    set gl(in_gl: GL | null);
    get rayPicker(): unknown;
    set rayPicker(in_rayPicker: unknown);
    set order(in_order: number);
    get order(): number;
    set insideSphere(v: boolean);
    get insideSphere(): boolean;
    get baseUrl(): string;
    get nsideForSelection(): number;
    get healpix4footprints(): boolean;
    get showConvexPolygons(): boolean;
    get showPointsInPolygons(): boolean;
    get blendMode(): boolean;
    getConfig_cameraFovDeg(): number;
    getConfig_nearPlane(): number;
    getConfig_cameraFarPlane(): number;
}
declare const global: Global;
export default global;
//# sourceMappingURL=Global.d.ts.map