import { MetadataColumn } from "./MetadataColumn.js";
export declare class MetadataManager {
    static STANDARD_SIZE: string;
    static STANDARD_HUE: string;
    private _outlineColumnList;
    private _raColumnList;
    private _decColumnList;
    private _shapeColumnList;
    private _hueColumnList;
    private _selectedOutlineColumn?;
    private _selectedRaColumn?;
    private _selectedDecColumn?;
    private _selectedShapeColumn?;
    private _selectedHueColumn?;
    private _selectedNameColumn?;
    private _columns;
    constructor(metadataColumns: MetadataColumn[]);
    addOutlineColumn(outlineColumn: MetadataColumn): void;
    addRaColumn(column: MetadataColumn): void;
    addDecColumn(column: MetadataColumn): void;
    addHueColumn(column: MetadataColumn): void;
    addShapeColumn(column: MetadataColumn): void;
    get selectedRaColumn(): MetadataColumn | undefined;
    get selectedDecColumn(): MetadataColumn | undefined;
    get selectedHueColumn(): MetadataColumn | undefined;
    get selectedShapeColumn(): MetadataColumn | undefined;
    get selectedOutlineColumn(): MetadataColumn | undefined;
    get selectedNameColumn(): MetadataColumn | undefined;
    get columns(): MetadataColumn[];
    get raColumnList(): MetadataColumn[];
    get decColumnList(): MetadataColumn[];
    get outlineColumnList(): MetadataColumn[];
    get hueColumnList(): MetadataColumn[];
    get shapeColumnList(): MetadataColumn[];
    set selectedRaColumn(columnName: string);
    set selectedDecColumn(columnName: string);
    set selectedOutlineColumn(columnName: string);
    set selectedHueColumn(columnName: string);
    set selectedShapeColumn(columnName: string);
    set selectedNameColumn(columnName: string);
    resetShapeColumn(): void;
    resetHueColumn(): void;
}
