import { ReadonlyMat4 } from 'gl-matrix';
import Camera from '../Camera.js';
import { AbstractSkyEntity } from './AbstractSkyEntity.js';
export declare class SphereFoV {
    private static readonly MIN_FOV_DEG;
    private fovXDeg;
    private fovYDeg;
    private ratio;
    private _minFoV;
    private _webgl;
    private _lastModel;
    private _lastCamera;
    constructor(webgl: WebGL2RenderingContext);
    getFoV(insideSphere: boolean, model: AbstractSkyEntity, camera: Camera, pMatrix: ReadonlyMat4): SphereFoV;
    private computeRatio;
    get minFoV(): number;
    get xFoV(): number;
    get yFoV(): number;
    computeDistanceFromAngle(angleDeg: number): number;
    changeMinFov(deg: number): void;
    computeCameraPositionForMinFoV(targetMinFoVDeg: number): [number, number, number];
    computeCameraPositionForFoV(targetFoVDeg: number): [number, number, number];
    computeCameraPositionForAngularDiameter(targetAngularDiameterDeg: number): [number, number, number];
    private computeAngle;
    private computeAngularDistanceDeg;
    private getIntersectionPointWithModel;
    private getRayFromMouse;
    private raySphere;
    private mat4MultiplyVec4;
}
