import { XYZShaderProgram } from '../../shader/XYZShaderProgram.js';
import type { XYZBufferedTile } from './XYZTileBuffer.js';
import { XYZMeshBuilder } from './XYZMeshBuilder.js';
import type { XYZTileCoord, XYZTileGpuMesh } from './XYZTypes.js';
type Mat4 = Float32Array;
export declare class XYZTile implements XYZBufferedTile {
    private _coord;
    private _url;
    private _webgl;
    private _shaderProgram;
    private _meshBuilder;
    private _gpuMesh;
    private _texture;
    private _image?;
    private _ready;
    private _loading;
    private _aborted;
    private _failedUntil;
    private _lastUsedAt;
    private _createdAt;
    constructor(coord: XYZTileCoord, url: string, webgl: WebGL2RenderingContext, shaderProgram: XYZShaderProgram, meshBuilder?: XYZMeshBuilder, segmentsPerSide?: number);
    get coord(): XYZTileCoord;
    get ready(): boolean;
    get loading(): boolean;
    get failedUntil(): number;
    get lastUsedAt(): number;
    get createdAt(): number;
    touch(): void;
    private initImage;
    private imageLoaded;
    private textureLoaded;
    draw(pMatrix: Mat4, vMatrix: Mat4, mMatrix: Mat4, colorMapIdx: number): boolean;
    drawRemapped(mesh: XYZTileGpuMesh, pMatrix: Mat4, vMatrix: Mat4, mMatrix: Mat4, colorMapIdx: number): boolean;
    dispose(): void;
    private drawWithGpuMesh;
    private get key();
}
export {};
